CREATE TABLE INFOS (
STUID VARCHAR2(7) NOT NULL , --学号 学号=‘S’+班号+2位序号
STUNAME VARCHAR2(10) NOT NULL, --姓名
GENDER VARCHAR2(2) NOT NULL,--性别
AGE NUMBER(2) NOT NULL, --年龄
SEAT NUMBER(2) NOT NULL, --座号
ENROLL DATE,--入学时间
STUADDRESS VARCHAR2(50) DEFAULT '地址不详', --住址
CLASSNO VARCHAR2(4) NOT NULL --班号 班号=学期序号+班级序号
);
select * from infos;
ALTER TABLE INFOS ADD CONSTRAINT PK_INFOS PRIMARY KEY(STUID);
ALTER TABLE INFOS ADD CONSTRAINT CK_INFOS_GENDER CHECK(GENDER='男' OR GENDER='女');
ALTER TABLE INFOS ADD CONSTRAINT CK_INFOS_SEAT CHECK(SEAT>=0 AND SEAT<=50); 

ALTER TABLE INFOS ADD CONSTRAINT CK_INFOS_AGE CHECK(AGE>=0 AND AGE<=100) ;
ALTER TABLE INFOS ADD CONSTRAINT CK_INFOS_CLASSNO CHECK((CLASSNO >='1001' AND CLASSNO<='1999') OR (CLASSNO >= '2001' AND CLASSNO<='2999'));
ALTER TABLE INFOS ADD CONSTRAINT UN_STUNAME UNIQUE(STUNAME); 
ALTER TABLE infos ADD CONSTRAINT FK_GENDER_ID FOREIGN KEY(CLASSNO) REFERENCES class(ID);

INSERT INTO INFOS VALUES ( 's100102','林冲','男', 22, 2,TO_DATE('2009-8-9 06:30:10',' YYYY-MM-DD HH24:MI:SS '),'西安','1001');
INSERT INTO INFOS VALUES ('s100104','阮小二','男',26,3,SYSDATE,default,'1001');

UPDATE INFOS SET CLASSNO='1002',STUADDRESS='山东莱芜' WHERE STUNAME='阮小二';
commit;
select * from emp MINUS select * from emp where deptno = 20;
select * from emp where ename like '%A%';


CREATE TABLE phone (PHONENUM VARCHAR2 (8),PAY number(8,2), NUMLEVEL VARCHAR(24),PAYDATE date);
INSERT INTO phone VALUES ('123456', 600,'pt04',to_date('2005-12-20','yyyy-MM--DD'));
INSERT INTO phone VALUES ('888888', 900,'pt05',to_date('2005-10-19','yyyy-MM--DD'));
SELECT * from phone; 
CREATE TABLE phone_bak AS SELECT * FROM phone;
select * from phone_bak;
UPDATE phone SET pay = 1000 where phonenum = '123456';

Rollback;
UPDATE phone SET NUMLEVEL = 'pt04' where phonenum = '888888';
commit;

